# Generated by Django 5.1.7 on 2025-04-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=100)),
                ("phone", models.CharField(max_length=100)),
                ("address", models.CharField(max_length=100)),
                ("course", models.CharField(max_length=100)),
                ("batch", models.CharField(max_length=100)),
                ("percentage_10", models.CharField(max_length=100)),
                ("percentage_12", models.CharField(max_length=100)),
                ("graduation_percentage", models.CharField(max_length=100)),
                ("current_location", models.CharField(max_length=100)),
                ("skills", models.TextField()),
                ("upload_resume", models.FileField(upload_to="resume/")),
            ],
        ),
    ]
